site_name: canine.tools
site_url: https://canine.tools
site_description: "Collection of open source web apps for canines and all!"

nav:
  - Home: index.md
  - About: about/index.md
  - Donate: donate/index.md
  - News: blog/index.md
  - Privacy: privacy/index.md
  - Services: services/index.md
  - Stats: stats/index.md
  - Terms: terms/index.md

repo_name: caninetools/canine.tools
repo_url: https://github.com/caninetools/canine.tools

copyright: |
  &copy; canine.tools - Happy barking!

plugins:
  - blog
  - glightbox
  - macros
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - redirects:
      redirect_maps:
        'stats/index.md': 'https://status.canine.tools'
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: true
theme:
  name: material
  custom_dir: 'theme'
  palette:
    scheme: slate
    primary: black
    accent: indigo
  logo: assets/images/logo-nt.png
  features:
    - navigation.instant.progress
    - navigation.tabs

markdown_extensions:
  - toc
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - assets/js/wolfy.js

extra_css:
  - assets/css/custom.css

#extra:
#  - '<link rel="icon" type="image/png" href="/assets/images/favicon-96x96.png" sizes="96x96" />'
#  - '<link rel="icon" type="image/svg+xml" href="/assets/images/favicon.svg" />'
#  - '<link rel="shortcut icon" href="/assets/images/favicon.ico" />'
#  - '<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/apple-touch-icon.png" />'
#  - '<meta name="apple-mobile-web-app-title" content="canine.tools" />'
#  - '<link rel="manifest" href="/assets/images/site.webmanifest" />'